"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { humanizeKey } from "@/lib/api";
import { markdownToPlainLines } from "@/lib/markdown";

const styles = StyleSheet.create({
  page: {
    paddingTop: 54,
    paddingBottom: 54,
    paddingHorizontal: 56,
    fontSize: 10,
    lineHeight: 1.5,
    fontFamily: "Helvetica",
    color: "#1a1a1a",
  },
  title: { fontSize: 20, fontFamily: "Helvetica-Bold", marginBottom: 12 },
  sectionLabel: {
    fontSize: 8,
    fontFamily: "Helvetica-Bold",
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 10,
  },
  value: { fontSize: 11, marginBottom: 2 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#e2e2e2", marginVertical: 14 },
  bodyLine: { textAlign: "justify", marginBottom: 6 },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 56,
    right: 56,
    fontSize: 7,
    color: "#999",
    textAlign: "center",
  },
});

type Props = {
  name: string;
  fields: Record<string, string>;
  markdown: string;
};

export function DocumentPdfDocument({ name, fields, markdown }: Props) {
  const entries = Object.entries(fields).filter(([, v]) => v && v.trim());
  const lines = markdownToPlainLines(markdown);

  return (
    <Document title={name}>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{name}</Text>
        {entries.map(([k, v]) => (
          <View key={k}>
            <Text style={styles.sectionLabel}>{humanizeKey(k)}</Text>
            <Text style={styles.value}>{v}</Text>
          </View>
        ))}
        <View style={styles.divider} />
        {lines.map((line, i) => (
          <Text key={i} style={styles.bodyLine}>
            {line}
          </Text>
        ))}
        <Text style={styles.footer} fixed>
          Draft generated by pre-legal — subject to legal review.
        </Text>
      </Page>
    </Document>
  );
}
